//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Caso
    {
        public int Evento_CasoId { get; set; }
        public Nullable<int> Registro_EventoId { get; set; }
        public Nullable<int> EventoId { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Registro_Evento Registro_Evento { get; set; }
    }
}
