//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implicado
    {
        public int Implicado_id { get; set; }
        public Nullable<int> Registro_Evento_id { get; set; }
        public Nullable<int> Profesion_id { get; set; }
        public Nullable<int> Rango_id { get; set; }
        public Nullable<int> Condicion_implicado_id { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
    
        public virtual Condicion_implicado Condicion_implicado { get; set; }
        public virtual Nacionalidad Nacionalidad1 { get; set; }
        public virtual Profesion Profesion { get; set; }
        public virtual Rango Rango { get; set; }
        public virtual Registro_Evento Registro_Evento { get; set; }
    }
}
