//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implicado
    {
        public int Implicado_id { get; set; }
        public Nullable<int> Registro_Evento_id { get; set; }
        public Nullable<int> Profesion_id { get; set; }
        public Nullable<int> Rango_id { get; set; }
        public Nullable<int> Condicion_implicado_id { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
    
        public virtual Condicion_implicado Condicion_implicado { get; set; }
        public virtual Nacionalidad Nacionalidad1 { get; set; }
        public virtual Profesion Profesion { get; set; }
        public virtual Rango Rango { get; set; }
        public virtual Registro_Evento Registro_Evento { get; set; }
    }
}
