//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro_Evento()
        {
            this.Evento_Caso = new HashSet<Evento_Caso>();
            this.Implicado = new HashSet<Implicado>();
        }
    
        public int Registro_EventoId { get; set; }
        public Nullable<int> RegionalId { get; set; }
        public Nullable<int> ComandanciaId { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> Tipo_InvolucradoId { get; set; }
        public decimal GeogCol1 { get; set; }
        public decimal GeogCol2 { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Fiscalizado { get; set; }
        public Nullable<bool> Retenido { get; set; }
        public string Comentario { get; set; }
        public string Numero_Caso { get; set; }
    
        public virtual Comandancia Comandancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento_Caso> Evento_Caso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Implicado> Implicado { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Regional Regional { get; set; }
        public virtual Tipo_Involucrado Tipo_Involucrado { get; set; }
        public virtual Zona Zona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
